import type {
  TravelRequestsWorkspaceTab,
} from "./composables/useTravelRequestsWorkspace"

import type {
  TravelRequestsOverviewItem,
} from "./components/TravelRequestsOverview.vue"

export const travelRequestsWorkspaceTabs: TravelRequestsWorkspaceTab[] =
  [
  {
    "key": "general",
    "label": "General",
    "labelKey": "hr.travel-requests.tabs.general",
    "type": "form",
    "fields": [
      "document_number",
      "employee",
      "rotation_period",
      "start_date",
      "end_date",
      "total_days",
      "status"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 10
  },
  {
    "key": "employee",
    "label": "Employee",
    "labelKey": "hr.travel-requests.tabs.employee",
    "type": "form",
    "fields": [
      "department_name",
      "section_name",
      "position_name",
      "work_email",
      "phone_number",
      "location_name",
      "employee_number",
      "join_date",
      "point_of_hire_name"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 20
  },
  {
    "key": "purposes",
    "label": "Travel Purpose",
    "labelKey": "hr.travel-requests.tabs.purposes",
    "type": "resource",
    "fields": [
      {
        "key": "purpose",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/rotation-purposes/",
        "tab": "general",
        "label": "Travel Purpose",
        "labelKey": "hr.travel-requests.purposes.fields.purpose",
        "display_key": "purpose_name",
        "lookup_params": {
          "document": "travel_request"
        },
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Field Break, Cuti Tahunan, dan cuti lain yang menumpang kepulangan site. Satu pengajuan boleh memuat beberapa baris beralasan berbeda. Dinas Luar/Training diajukan lewat Business Trip.",
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/rotation-purposes/",
        "dependsOn": null,
        "lookupParams": {
          "document": "travel_request"
        },
        "displayKey": "purpose_name"
      },
      {
        "key": "start_date",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "From",
        "labelKey": "hr.travel-requests.purposes.fields.start_date",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "start_date"
      },
      {
        "key": "end_date",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "Sampai",
        "labelKey": "hr.travel-requests.purposes.fields.end_date",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "end_date"
      },
      {
        "key": "total_days",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Days",
        "labelKey": "hr.travel-requests.purposes.fields.total_days",
        "compute": {
          "kind": "date_diff",
          "from": "start_date",
          "to": "end_date",
          "inclusive": true
        },
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "total_days"
      },
      {
        "key": "deducts_leave",
        "type": "boolean",
        "widget": "switch",
        "tab": "general",
        "label": "Deducts Leave",
        "labelKey": "hr.travel-requests.purposes.fields.deducts_leave",
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": false,
        "disabled": true,
        "help_text": "Turunan dari master Travel Purpose. Field Break tidak memotong saldo; Cuti Tahunan memotong, dan catatan cutinya diterbitkan otomatis saat pengajuan disetujui.",
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "deducts_leave"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 2,
        "tab": "general",
        "label": "Remarks",
        "labelKey": "hr.travel-requests.purposes.fields.notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/travel-request-purposes/",
    "module": "hr/travel-request-purposes",
    "foreignKey": "request",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": true,
    "canCreate": true,
    "readonlyWhen": {
      "field": "is_editable",
      "op": "is_false"
    },
    "showOnCreate": true,
    "order": 30
  },
  {
    "key": "travels",
    "label": "Travel Arrangement",
    "labelKey": "hr.travel-requests.tabs.travels",
    "type": "resource",
    "fields": [
      {
        "key": "direction",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "label": "Outbound",
            "value": "out"
          },
          {
            "label": "Inbound",
            "value": "in"
          }
        ],
        "tab": "general",
        "label": "Direction",
        "labelKey": "hr.travel-requests.travels.fields.direction",
        "display_key": "direction_label",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Outbound = pulang dari site. Inbound = kembali ke site. Satu arah boleh terdiri dari beberapa etape.",
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "direction_label"
      },
      {
        "key": "sequence",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Leg",
        "labelKey": "hr.travel-requests.travels.fields.sequence",
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "help_text": "Urutan etape dalam satu arah. Dikosongkan = nomor bebas berikutnya. Jakarta → Sorong = 1, Sorong → Gebe = 2.",
        "order": 15,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "sequence"
      },
      {
        "key": "travel_start_date",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "Departure Date",
        "labelKey": "hr.travel-requests.travels.fields.travel_start_date",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "travel_start_date"
      },
      {
        "key": "travel_end_date",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "Arrival Date",
        "labelKey": "hr.travel-requests.travels.fields.travel_end_date",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "help_text": "Dikosongkan = tiba di hari yang sama.",
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "travel_end_date"
      },
      {
        "key": "origin",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "From",
        "labelKey": "hr.travel-requests.travels.fields.origin",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "placeholder": "mis. Gebe",
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "origin"
      },
      {
        "key": "destination",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "To",
        "labelKey": "hr.travel-requests.travels.fields.destination",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "placeholder": "mis. Jakarta",
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "destination"
      },
      {
        "key": "transport_mode",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/transport-modes/",
        "tab": "general",
        "label": "Transport Mode",
        "labelKey": "hr.travel-requests.travels.fields.transport_mode",
        "display_key": "transport_mode_name",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 60,
        "endpoint": "/api/administration/references/hr/lookup/transport-modes/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "transport_mode_name"
      },
      {
        "key": "transport_detail",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Transport Detail",
        "labelKey": "hr.travel-requests.travels.fields.transport_detail",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "placeholder": "mis. GA-642 / KM Sabuk Nusantara",
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "transport_detail"
      },
      {
        "key": "ticket_number",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Ticket Number",
        "labelKey": "hr.travel-requests.travels.fields.ticket_number",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "ticket_number"
      },
      {
        "key": "justification",
        "type": "textarea",
        "widget": "textarea",
        "rows": 2,
        "tab": "general",
        "label": "Justification",
        "labelKey": "hr.travel-requests.travels.fields.justification",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "help_text": "Alasan perjalanan ini menyimpang dari rotasi normal. Kosong = perjalanan rutin.",
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "justification"
      },
      {
        "key": "counts_as_work",
        "type": "boolean",
        "widget": "switch",
        "tab": "general",
        "label": "Counts As Work",
        "labelKey": "hr.travel-requests.travels.fields.counts_as_work",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "help_text": "Menyala sendiri untuk Kepulangan (kembali ke site). Boleh dinyalakan untuk keberangkatan yang tertunda.",
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "counts_as_work"
      },
      {
        "key": "is_special_arrangement",
        "type": "boolean",
        "widget": "switch",
        "tab": "general",
        "label": "Special Arrangement",
        "labelKey": "hr.travel-requests.travels.fields.is_special_arrangement",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "help_text": "Charter, evakuasi medis, rombongan keluarga.",
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_special_arrangement"
      },
      {
        "key": "special_arrangement_notes",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Arrangement Detail",
        "labelKey": "hr.travel-requests.travels.fields.special_arrangement_notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "special_arrangement_notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/travel-arrangements/",
    "module": "hr/travel-arrangements",
    "foreignKey": "request",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": true,
    "canCreate": true,
    "readonlyWhen": {
      "field": "is_editable",
      "op": "is_false"
    },
    "showOnCreate": true,
    "order": 40
  },
  {
    "key": "accommodation",
    "label": "Accommodation",
    "labelKey": "hr.travel-requests.tabs.accommodation",
    "type": "resource",
    "fields": [
      {
        "key": "direction",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "label": "Outbound",
            "value": "out"
          },
          {
            "label": "Inbound",
            "value": "in"
          }
        ],
        "tab": "general",
        "label": "Direction",
        "labelKey": "hr.travel-requests.accommodation.fields.direction",
        "display_key": "direction_label",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Outbound = pulang dari site. Inbound = kembali ke site. Satu arah boleh terdiri dari beberapa etape.",
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "direction_label"
      },
      {
        "key": "sequence",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Leg",
        "labelKey": "hr.travel-requests.accommodation.fields.sequence",
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "help_text": "Urutan etape dalam satu arah. Dikosongkan = nomor bebas berikutnya. Jakarta → Sorong = 1, Sorong → Gebe = 2.",
        "order": 15,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "sequence"
      },
      {
        "key": "origin",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "From",
        "labelKey": "hr.travel-requests.accommodation.fields.origin",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "placeholder": "mis. Gebe",
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "origin"
      },
      {
        "key": "destination",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "To",
        "labelKey": "hr.travel-requests.accommodation.fields.destination",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "placeholder": "mis. Jakarta",
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "destination"
      },
      {
        "key": "accommodation_type",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/accommodation-types/",
        "tab": "accommodation",
        "label": "Accommodation Type",
        "labelKey": "hr.travel-requests.accommodation.fields.accommodation_type",
        "display_key": "accommodation_type_name",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 220,
        "endpoint": "/api/administration/references/hr/lookup/accommodation-types/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "accommodation_type_name"
      },
      {
        "key": "accommodation_name",
        "type": "text",
        "widget": "text",
        "tab": "accommodation",
        "label": "Accommodation Name",
        "labelKey": "hr.travel-requests.accommodation.fields.accommodation_name",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "placeholder": "mis. Hotel Bukit Pelangi",
        "order": 230,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "accommodation_name"
      },
      {
        "key": "accommodation_checkin",
        "type": "date",
        "widget": "date",
        "tab": "accommodation",
        "label": "Check-in",
        "labelKey": "hr.travel-requests.accommodation.fields.accommodation_checkin",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 240,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "accommodation_checkin"
      },
      {
        "key": "accommodation_checkout",
        "type": "date",
        "widget": "date",
        "tab": "accommodation",
        "label": "Check-out",
        "labelKey": "hr.travel-requests.accommodation.fields.accommodation_checkout",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 250,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "accommodation_checkout"
      },
      {
        "key": "accommodation_nights",
        "type": "integer",
        "widget": "integer",
        "tab": "accommodation",
        "label": "Nights",
        "labelKey": "hr.travel-requests.accommodation.fields.accommodation_nights",
        "compute": {
          "kind": "date_diff",
          "from": "accommodation_checkin",
          "to": "accommodation_checkout",
          "inclusive": false
        },
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "disabled": true,
        "order": 260,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "accommodation_nights"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 2,
        "tab": "accommodation",
        "label": "Notes",
        "labelKey": "hr.travel-requests.accommodation.fields.notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 270,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/travel-arrangements/",
    "module": "hr/travel-arrangements",
    "foreignKey": "request",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": true,
    "canCreate": true,
    "readonlyWhen": {
      "field": "is_editable",
      "op": "is_false"
    },
    "canDelete": false,
    "description": "Each stay belongs to a trip leg. Adding a row here also adds a leg — complete or correct it in Travel Arrangement. To remove a stay, clear its fields and save; the leg stays.",
    "descriptionKey": "hr.travel-requests.tabHints.accommodation",
    "showOnCreate": true,
    "order": 50
  },
  {
    "key": "notes",
    "label": "Notes",
    "labelKey": "hr.travel-requests.tabs.notes",
    "type": "form",
    "fields": [
      "notes"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 60
  }
]

export const travelRequestsWorkspaceDefaultTab: string =
  "general"

export const travelRequestsOverviewItems: TravelRequestsOverviewItem[] =
  [
  {
    key: "document_number",
    label: "TR No.",
    fallback: "-",
  },
  {
    key: "employee_name",
    label: "Employee",
    fallback: "-",
  },
  {
    key: "start_date",
    label: "Off Start",
    fallback: "-",
  },
  {
    key: "end_date",
    label: "Off End",
    fallback: "-",
  },
  {
    key: "status_label",
    label: "Status",
    fallback: "-",
  }
]