import type {
  EmployeesWorkspaceTab,
} from "./composables/useEmployeesWorkspace"

import type {
  EmployeesOverviewItem,
} from "./components/EmployeesOverview.vue"

export const employeesWorkspaceTabs: EmployeesWorkspaceTab[] =
  [
  {
    "key": "general",
    "label": "General",
    "labelKey": "hr.employees.tabs.general",
    "type": "form",
    "fields": [
      "user",
      "auto_generate_employee_number",
      "employee_number",
      "nik",
      "passport_number",
      "tax_number",
      "first_name",
      "last_name",
      "gender",
      "religion",
      "nationality",
      "nationality_code",
      "blood_type",
      "marital_status",
      "birth_place",
      "birth_date",
      "province",
      "city",
      "district",
      "village",
      "address",
      "personal_email",
      "work_email",
      "phone",
      "mobile",
      "emergency_contact_name",
      "emergency_contact_phone",
      "avatar_file",
      "avatar",
      "notes",
      "is_active"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 10
  },
  {
    "key": "organization",
    "label": "Organization",
    "labelKey": "hr.employees.tabs.organization",
    "type": "form",
    "fields": [
      "company",
      "branch",
      "location",
      "division",
      "department",
      "section",
      "position",
      "job_level",
      "job_grade",
      "reports_to",
      "cost_center",
      "organization_effective_date",
      "organization_notes"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 20
  },
  {
    "key": "employment",
    "label": "Current Employment",
    "labelKey": "hr.employees.tabs.employment",
    "type": "form",
    "fields": [
      "employment_status",
      "employment_type",
      "employee_group",
      "employment_effective_date",
      "join_date",
      "job_location",
      "point_of_hire",
      "confirmation_date",
      "notice_period_days",
      "employment_notes"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 30
  },
  {
    "key": "contract",
    "label": "Contract & Probation",
    "labelKey": "hr.employees.tabs.contract",
    "type": "form",
    "fields": [
      "employment_type_requires_contract",
      "contract_type",
      "probation_type",
      "probation_start",
      "probation_end",
      "contract_start",
      "contract_end"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 32
  },
  {
    "key": "work_arrangement",
    "label": "Work Arrangement",
    "labelKey": "hr.employees.tabs.work_arrangement",
    "type": "form",
    "fields": [
      "roster_policy",
      "roster_cycle_start",
      "roster_crew",
      "work_schedule",
      "working_calendar",
      "employee_group_shift_applicable",
      "employee_group_roster_applicable",
      "shift",
      "roster_start_override",
      "back_to_back_partner",
      "travel_days_override"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 34
  },
  {
    "key": "payroll",
    "label": "Payroll",
    "labelKey": "hr.employees.tabs.payroll",
    "type": "resource",
    "fields": [
      {
        "key": "payroll_group",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/payroll-groups/lookup/",
        "tab": "payroll",
        "label": "Payroll Group",
        "labelKey": "hr.employees.payroll.fields.payroll_group",
        "required": true,
        "table": false,
        "filter": true,
        "order": 10,
        "endpoint": "/api/payroll/payroll-groups/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "payroll_group_name"
      },
      {
        "key": "salary_grade",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/salary-grades/lookup/",
        "tab": "payroll",
        "label": "Salary Grade",
        "labelKey": "hr.employees.payroll.fields.salary_grade",
        "table": false,
        "filter": true,
        "order": 20,
        "endpoint": "/api/payroll/salary-grades/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "salary_grade_name"
      },
      {
        "key": "salary_level",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/salary-levels/lookup/",
        "tab": "payroll",
        "label": "Salary Level",
        "labelKey": "hr.employees.payroll.fields.salary_level",
        "depends_on": "salary_grade",
        "lookup_params": {
          "salary_grade_id": "$salary_grade"
        },
        "table": false,
        "order": 30,
        "endpoint": "/api/payroll/salary-levels/lookup/",
        "dependsOn": "salary_grade",
        "lookupParams": {
          "salary_grade_id": "$salary_grade"
        },
        "displayKey": "salary_level_name"
      },
      {
        "key": "currency",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/currency/lookup/currencies/",
        "tab": "payroll",
        "label": "Currency",
        "labelKey": "hr.employees.payroll.fields.currency",
        "required": true,
        "table": false,
        "order": 40,
        "endpoint": "/api/administration/currency/lookup/currencies/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "currency_name"
      },
      {
        "key": "payment_method",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "label": "Bank Transfer",
            "value": "bank_transfer"
          },
          {
            "label": "Cash",
            "value": "cash"
          },
          {
            "label": "Cheque",
            "value": "cheque"
          }
        ],
        "tab": "payroll",
        "label": "Payment Method",
        "labelKey": "hr.employees.payroll.fields.payment_method",
        "default": "bank_transfer",
        "table": false,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "payment_method"
      },
      {
        "key": "tax_status",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/tax-statuses/lookup/",
        "tab": "payroll",
        "label": "Tax Status",
        "labelKey": "hr.employees.payroll.fields.tax_status",
        "table": false,
        "filter": true,
        "order": 60,
        "endpoint": "/api/payroll/tax-statuses/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "tax_status_name"
      },
      {
        "key": "tax_number_payroll",
        "type": "text",
        "widget": "text",
        "tab": "payroll",
        "label": "Tax Number",
        "labelKey": "hr.employees.payroll.fields.tax_number_payroll",
        "permission": "payroll.view_employee_payroll",
        "table": false,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "tax_number_payroll"
      },
      {
        "key": "bpjs_kesehatan_number",
        "type": "text",
        "widget": "text",
        "tab": "payroll",
        "label": "BPJS Kesehatan Number",
        "labelKey": "hr.employees.payroll.fields.bpjs_kesehatan_number",
        "permission": "payroll.view_employee_payroll",
        "table": false,
        "filter": false,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "bpjs_kesehatan_number"
      },
      {
        "key": "bpjs_ketenagakerjaan_number",
        "type": "text",
        "widget": "text",
        "tab": "payroll",
        "label": "BPJS Ketenagakerjaan Number",
        "labelKey": "hr.employees.payroll.fields.bpjs_ketenagakerjaan_number",
        "permission": "payroll.view_employee_payroll",
        "table": false,
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "bpjs_ketenagakerjaan_number"
      },
      {
        "key": "overtime_eligible",
        "type": "boolean",
        "widget": "switch",
        "tab": "payroll",
        "label": "Overtime Eligible",
        "labelKey": "hr.employees.payroll.fields.overtime_eligible",
        "default": false,
        "table": false,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "overtime_eligible"
      },
      {
        "key": "overtime_group",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/overtime-groups/lookup/",
        "tab": "payroll",
        "label": "Overtime Group",
        "labelKey": "hr.employees.payroll.fields.overtime_group",
        "table": false,
        "order": 110,
        "endpoint": "/api/payroll/overtime-groups/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "overtime_group_name"
      },
      {
        "key": "payroll_policy",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/payroll-policies/lookup/",
        "tab": "payroll",
        "label": "Payroll Policy",
        "labelKey": "hr.employees.payroll.fields.payroll_policy",
        "table": false,
        "filter": true,
        "order": 115,
        "help_text": "Dikosongkan = ikut Payroll Setting perusahaan. Dipakai kalau kelompok pegawai ini dihitung berbeda dari default perusahaannya.",
        "endpoint": "/api/payroll/payroll-policies/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "payroll_policy_name"
      },
      {
        "key": "effective_from",
        "type": "date",
        "widget": "date",
        "tab": "payroll",
        "label": "Effective From",
        "labelKey": "hr.employees.payroll.fields.effective_from",
        "required": true,
        "table": false,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "effective_from"
      },
      {
        "key": "effective_to",
        "type": "date",
        "widget": "date",
        "tab": "payroll",
        "label": "Effective To",
        "labelKey": "hr.employees.payroll.fields.effective_to",
        "table": false,
        "order": 125,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "effective_to"
      },
      {
        "key": "basic_salary",
        "type": "currency",
        "widget": "currency",
        "tab": "payroll",
        "label": "Basic Salary",
        "labelKey": "hr.employees.payroll.fields.basic_salary",
        "min": 0,
        "permission": "payroll.view_salary",
        "table": false,
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "basic_salary"
      },
      {
        "key": "daily_rate",
        "type": "currency",
        "widget": "currency",
        "tab": "payroll",
        "label": "Daily Rate",
        "labelKey": "hr.employees.payroll.fields.daily_rate",
        "min": 0,
        "permission": "payroll.view_salary",
        "table": false,
        "order": 135,
        "help_text": "Upah sehari. Hanya dipakai kalau Payroll Policy pegawai ini berdasar Harian dan tarifnya memang diambil dari sini.",
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "daily_rate"
      },
      {
        "key": "allowance_template",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/allowance-templates/lookup/",
        "tab": "payroll",
        "label": "Allowance Template",
        "labelKey": "hr.employees.payroll.fields.allowance_template",
        "table": false,
        "order": 140,
        "endpoint": "/api/payroll/allowance-templates/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "allowance_template_name"
      },
      {
        "key": "deduction_template",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/payroll/deduction-templates/lookup/",
        "tab": "payroll",
        "label": "Deduction Template",
        "labelKey": "hr.employees.payroll.fields.deduction_template",
        "table": false,
        "order": 150,
        "endpoint": "/api/payroll/deduction-templates/lookup/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "deduction_template_name"
      },
      {
        "key": "payroll_notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 4,
        "tab": "payroll",
        "label": "Payroll Notes",
        "labelKey": "hr.employees.payroll.fields.payroll_notes",
        "layout": "full",
        "permission": "payroll.view_employee_payroll",
        "table": false,
        "order": 160,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "payroll_notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/payroll-assignments/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 40
  },
  {
    "key": "bank",
    "label": "Bank Accounts",
    "labelKey": "hr.employees.tabs.bank",
    "type": "resource",
    "fields": [
      {
        "key": "bank",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/bank/lookup/banks/",
        "tab": "bank",
        "label": "Bank",
        "labelKey": "hr.employees.bank.fields.bank",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/bank/lookup/banks/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "bank_name"
      },
      {
        "key": "branch_name",
        "type": "text",
        "widget": "text",
        "tab": "bank",
        "label": "Branch",
        "labelKey": "hr.employees.bank.fields.branch_name",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "branch_name"
      },
      {
        "key": "account_number",
        "type": "text",
        "widget": "text",
        "tab": "bank",
        "label": "Account Number",
        "labelKey": "hr.employees.bank.fields.account_number",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "account_number"
      },
      {
        "key": "account_name",
        "type": "text",
        "widget": "text",
        "tab": "bank",
        "label": "Account Holder",
        "labelKey": "hr.employees.bank.fields.account_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "account_name"
      },
      {
        "key": "currency",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/currency/lookup/currencies/",
        "tab": "bank",
        "label": "Currency",
        "labelKey": "hr.employees.bank.fields.currency",
        "display_key": "currency_code",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 50,
        "endpoint": "/api/administration/currency/lookup/currencies/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "currency_code"
      },
      {
        "key": "swift_code",
        "type": "text",
        "widget": "text",
        "tab": "bank",
        "label": "SWIFT Code",
        "labelKey": "hr.employees.bank.fields.swift_code",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "swift_code"
      },
      {
        "key": "iban",
        "type": "text",
        "widget": "text",
        "tab": "bank",
        "label": "IBAN",
        "labelKey": "hr.employees.bank.fields.iban",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "iban"
      },
      {
        "key": "is_primary",
        "type": "boolean",
        "widget": "switch",
        "tab": "bank",
        "label": "Primary Account",
        "labelKey": "hr.employees.bank.fields.is_primary",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_primary"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "bank",
        "label": "Active",
        "labelKey": "hr.employees.bank.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "bank",
        "label": "Notes",
        "labelKey": "hr.employees.bank.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-bank-accounts/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 50
  },
  {
    "key": "family",
    "label": "Family",
    "labelKey": "hr.employees.tabs.family",
    "type": "resource",
    "fields": [
      {
        "key": "relationship",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/family-relationships/",
        "tab": "family",
        "label": "Relationship",
        "labelKey": "hr.employees.family.fields.relationship",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/family-relationships/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "relationship_name"
      },
      {
        "key": "full_name",
        "type": "text",
        "widget": "text",
        "tab": "family",
        "label": "Full Name",
        "labelKey": "hr.employees.family.fields.full_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "full_name"
      },
      {
        "key": "gender",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/genders/",
        "tab": "family",
        "label": "Gender",
        "labelKey": "hr.employees.family.fields.gender",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 30,
        "endpoint": "/api/administration/references/hr/lookup/genders/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "gender_name"
      },
      {
        "key": "birth_place",
        "type": "text",
        "widget": "text",
        "tab": "family",
        "label": "Birth Place",
        "labelKey": "hr.employees.family.fields.birth_place",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "birth_place"
      },
      {
        "key": "birth_date",
        "type": "date",
        "widget": "date",
        "tab": "family",
        "label": "Birth Date",
        "labelKey": "hr.employees.family.fields.birth_date",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "birth_date"
      },
      {
        "key": "occupation",
        "type": "text",
        "widget": "text",
        "tab": "family",
        "label": "Occupation",
        "labelKey": "hr.employees.family.fields.occupation",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "occupation"
      },
      {
        "key": "phone",
        "type": "text",
        "widget": "text",
        "tab": "family",
        "label": "Phone",
        "labelKey": "hr.employees.family.fields.phone",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "phone"
      },
      {
        "key": "is_dependent",
        "type": "boolean",
        "widget": "switch",
        "tab": "family",
        "label": "Dependent",
        "labelKey": "hr.employees.family.fields.is_dependent",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_dependent"
      },
      {
        "key": "is_emergency_contact",
        "type": "boolean",
        "widget": "switch",
        "tab": "family",
        "label": "Emergency Contact",
        "labelKey": "hr.employees.family.fields.is_emergency_contact",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_emergency_contact"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "family",
        "label": "Active",
        "labelKey": "hr.employees.family.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "family",
        "label": "Notes",
        "labelKey": "hr.employees.family.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-families/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 60
  },
  {
    "key": "education",
    "label": "Education",
    "labelKey": "hr.employees.tabs.education",
    "type": "resource",
    "fields": [
      {
        "key": "education",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/education-levels/",
        "tab": "education",
        "label": "Education Level",
        "labelKey": "hr.employees.education.fields.education",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/education-levels/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "education_name"
      },
      {
        "key": "degree",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/degrees/",
        "tab": "education",
        "label": "Degree",
        "labelKey": "hr.employees.education.fields.degree",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 20,
        "endpoint": "/api/administration/references/hr/lookup/degrees/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "degree_name"
      },
      {
        "key": "study_field",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/study-fields/",
        "tab": "education",
        "label": "Study Field",
        "labelKey": "hr.employees.education.fields.study_field",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 30,
        "endpoint": "/api/administration/references/hr/lookup/study-fields/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "study_field_name"
      },
      {
        "key": "institution_name",
        "type": "text",
        "widget": "text",
        "tab": "education",
        "label": "Institution",
        "labelKey": "hr.employees.education.fields.institution_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "institution_name"
      },
      {
        "key": "city",
        "type": "text",
        "widget": "text",
        "tab": "education",
        "label": "City",
        "labelKey": "hr.employees.education.fields.city",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "city"
      },
      {
        "key": "country",
        "type": "text",
        "widget": "text",
        "tab": "education",
        "label": "Country",
        "labelKey": "hr.employees.education.fields.country",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "country"
      },
      {
        "key": "start_date",
        "type": "date",
        "widget": "date",
        "tab": "education",
        "label": "Start Date",
        "labelKey": "hr.employees.education.fields.start_date",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "start_date"
      },
      {
        "key": "end_date",
        "type": "date",
        "widget": "date",
        "tab": "education",
        "label": "End Date",
        "labelKey": "hr.employees.education.fields.end_date",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "end_date"
      },
      {
        "key": "graduation_year",
        "type": "number",
        "widget": "number",
        "min": 1900,
        "tab": "education",
        "label": "Graduation Year",
        "labelKey": "hr.employees.education.fields.graduation_year",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "graduation_year"
      },
      {
        "key": "gpa",
        "type": "number",
        "widget": "number",
        "min": 0,
        "max": 4,
        "step": 0.01,
        "tab": "education",
        "label": "GPA",
        "labelKey": "hr.employees.education.fields.gpa",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "gpa"
      },
      {
        "key": "certificate_number",
        "type": "text",
        "widget": "text",
        "tab": "education",
        "label": "Certificate Number",
        "labelKey": "hr.employees.education.fields.certificate_number",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "certificate_number"
      },
      {
        "key": "is_highest_education",
        "type": "boolean",
        "widget": "switch",
        "tab": "education",
        "label": "Highest Education",
        "labelKey": "hr.employees.education.fields.is_highest_education",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_highest_education"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "education",
        "label": "Active",
        "labelKey": "hr.employees.education.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "education",
        "label": "Notes",
        "labelKey": "hr.employees.education.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 140,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-educations/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 70
  },
  {
    "key": "experience",
    "label": "Experience",
    "labelKey": "hr.employees.tabs.experience",
    "type": "resource",
    "fields": [
      {
        "key": "company_name",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Company Name",
        "labelKey": "hr.employees.experience.fields.company_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "company_name"
      },
      {
        "key": "position_name",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Position",
        "labelKey": "hr.employees.experience.fields.position_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "position_name"
      },
      {
        "key": "employment_type",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Employment Type",
        "labelKey": "hr.employees.experience.fields.employment_type",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "employment_type"
      },
      {
        "key": "industry",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Industry",
        "labelKey": "hr.employees.experience.fields.industry",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "industry"
      },
      {
        "key": "location",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Location",
        "labelKey": "hr.employees.experience.fields.location",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "location"
      },
      {
        "key": "start_date",
        "type": "date",
        "widget": "date",
        "tab": "experience",
        "label": "Start Date",
        "labelKey": "hr.employees.experience.fields.start_date",
        "required": true,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "start_date"
      },
      {
        "key": "end_date",
        "type": "date",
        "widget": "date",
        "tab": "experience",
        "label": "End Date",
        "labelKey": "hr.employees.experience.fields.end_date",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "end_date"
      },
      {
        "key": "is_current",
        "type": "boolean",
        "widget": "switch",
        "tab": "experience",
        "label": "Current Employment",
        "labelKey": "hr.employees.experience.fields.is_current",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_current"
      },
      {
        "key": "last_salary",
        "type": "number",
        "widget": "number",
        "min": 0,
        "step": 0.01,
        "tab": "experience",
        "label": "Last Salary",
        "labelKey": "hr.employees.experience.fields.last_salary",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "last_salary"
      },
      {
        "key": "job_description",
        "type": "textarea",
        "widget": "textarea",
        "rows": 4,
        "tab": "experience",
        "label": "Job Description",
        "labelKey": "hr.employees.experience.fields.job_description",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "job_description"
      },
      {
        "key": "reason_for_leaving",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "experience",
        "label": "Reason for Leaving",
        "labelKey": "hr.employees.experience.fields.reason_for_leaving",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "reason_for_leaving"
      },
      {
        "key": "reference_name",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Reference Name",
        "labelKey": "hr.employees.experience.fields.reference_name",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "reference_name"
      },
      {
        "key": "reference_phone",
        "type": "text",
        "widget": "text",
        "tab": "experience",
        "label": "Reference Phone",
        "labelKey": "hr.employees.experience.fields.reference_phone",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "reference_phone"
      },
      {
        "key": "is_verified",
        "type": "boolean",
        "widget": "switch",
        "tab": "experience",
        "label": "Verified",
        "labelKey": "hr.employees.experience.fields.is_verified",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 140,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_verified"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "experience",
        "label": "Active",
        "labelKey": "hr.employees.experience.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 150,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "experience",
        "label": "Notes",
        "labelKey": "hr.employees.experience.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 160,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-experiences/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 80
  },
  {
    "key": "certificate",
    "label": "Certificates",
    "labelKey": "hr.employees.tabs.certificate",
    "type": "resource",
    "fields": [
      {
        "key": "certificate_type",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/certificate-types/",
        "tab": "certificate",
        "label": "Certificate Type",
        "labelKey": "hr.employees.certificate.fields.certificate_type",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/certificate-types/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "certificate_type_name"
      },
      {
        "key": "certificate_name",
        "type": "text",
        "widget": "text",
        "tab": "certificate",
        "label": "Certificate Name",
        "labelKey": "hr.employees.certificate.fields.certificate_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "certificate_name"
      },
      {
        "key": "certificate_number",
        "type": "text",
        "widget": "text",
        "tab": "certificate",
        "label": "Certificate Number",
        "labelKey": "hr.employees.certificate.fields.certificate_number",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "certificate_number"
      },
      {
        "key": "issuing_organization",
        "type": "text",
        "widget": "text",
        "tab": "certificate",
        "label": "Issuing Organization",
        "labelKey": "hr.employees.certificate.fields.issuing_organization",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "issuing_organization"
      },
      {
        "key": "issue_date",
        "type": "date",
        "widget": "date",
        "tab": "certificate",
        "label": "Issue Date",
        "labelKey": "hr.employees.certificate.fields.issue_date",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "issue_date"
      },
      {
        "key": "expiry_date",
        "type": "date",
        "widget": "date",
        "tab": "certificate",
        "label": "Expiry Date",
        "labelKey": "hr.employees.certificate.fields.expiry_date",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "expiry_date"
      },
      {
        "key": "credential_id",
        "type": "text",
        "widget": "text",
        "tab": "certificate",
        "label": "Credential ID",
        "labelKey": "hr.employees.certificate.fields.credential_id",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "credential_id"
      },
      {
        "key": "credential_url",
        "type": "text",
        "widget": "text",
        "tab": "certificate",
        "label": "Credential URL",
        "labelKey": "hr.employees.certificate.fields.credential_url",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "credential_url"
      },
      {
        "key": "uploaded_file",
        "type": "file",
        "widget": "upload",
        "accept": [
          "pdf",
          "jpg",
          "jpeg",
          "png",
          "doc",
          "docx"
        ],
        "multiple": false,
        "category": "attachment",
        "public": false,
        "preview": true,
        "download": true,
        "replace": true,
        "delete": true,
        "upload_endpoint": "/api/uploads/",
        "tab": "certificate",
        "label": "Attachment",
        "labelKey": "hr.employees.certificate.fields.uploaded_file",
        "required": false,
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 90,
        "value_mode": "id",
        "upload_mode": "separate",
        "detail_field": "uploaded_file_detail",
        "export": false,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "uploaded_file"
      },
      {
        "key": "is_lifetime",
        "type": "boolean",
        "widget": "switch",
        "tab": "certificate",
        "label": "Lifetime Certificate",
        "labelKey": "hr.employees.certificate.fields.is_lifetime",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_lifetime"
      },
      {
        "key": "is_verified",
        "type": "boolean",
        "widget": "switch",
        "tab": "certificate",
        "label": "Verified",
        "labelKey": "hr.employees.certificate.fields.is_verified",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_verified"
      },
      {
        "key": "verification_notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "certificate",
        "label": "Verification Notes",
        "labelKey": "hr.employees.certificate.fields.verification_notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "verification_notes"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "certificate",
        "label": "Active",
        "labelKey": "hr.employees.certificate.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "certificate",
        "label": "Notes",
        "labelKey": "hr.employees.certificate.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 140,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-certificates/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 90
  },
  {
    "key": "document",
    "label": "Documents",
    "labelKey": "hr.employees.tabs.document",
    "type": "resource",
    "fields": [
      {
        "key": "document_type",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/document-types/",
        "tab": "document",
        "label": "Document Type",
        "labelKey": "hr.employees.document.fields.document_type",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/document-types/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "document_type_name"
      },
      {
        "key": "document_name",
        "type": "text",
        "widget": "text",
        "tab": "document",
        "label": "Document Name",
        "labelKey": "hr.employees.document.fields.document_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "document_name"
      },
      {
        "key": "document_number",
        "type": "text",
        "widget": "text",
        "tab": "document",
        "label": "Document Number",
        "labelKey": "hr.employees.document.fields.document_number",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "document_number"
      },
      {
        "key": "issue_date",
        "type": "date",
        "widget": "date",
        "tab": "document",
        "label": "Issue Date",
        "labelKey": "hr.employees.document.fields.issue_date",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "issue_date"
      },
      {
        "key": "expiry_date",
        "type": "date",
        "widget": "date",
        "tab": "document",
        "label": "Expiry Date",
        "labelKey": "hr.employees.document.fields.expiry_date",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "expiry_date"
      },
      {
        "key": "issuing_authority",
        "type": "text",
        "widget": "text",
        "tab": "document",
        "label": "Issuing Authority",
        "labelKey": "hr.employees.document.fields.issuing_authority",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "issuing_authority"
      },
      {
        "key": "uploaded_file",
        "type": "file",
        "widget": "upload",
        "accept": [
          "pdf",
          "jpg",
          "jpeg",
          "png",
          "doc",
          "docx"
        ],
        "multiple": false,
        "category": "attachment",
        "public": false,
        "preview": true,
        "download": true,
        "replace": true,
        "delete": true,
        "upload_endpoint": "/api/uploads/",
        "tab": "document",
        "label": "Attachment",
        "labelKey": "hr.employees.document.fields.uploaded_file",
        "required": false,
        "order": 70,
        "value_mode": "id",
        "upload_mode": "separate",
        "detail_field": "uploaded_file_detail",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "export": false,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "uploaded_file"
      },
      {
        "key": "is_required",
        "type": "boolean",
        "widget": "switch",
        "tab": "document",
        "label": "Required Document",
        "labelKey": "hr.employees.document.fields.is_required",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_required"
      },
      {
        "key": "is_verified",
        "type": "boolean",
        "widget": "switch",
        "tab": "document",
        "label": "Verified",
        "labelKey": "hr.employees.document.fields.is_verified",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_verified"
      },
      {
        "key": "verification_notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "document",
        "label": "Verification Notes",
        "labelKey": "hr.employees.document.fields.verification_notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "verification_notes"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "document",
        "label": "Active",
        "labelKey": "hr.employees.document.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "document",
        "label": "Notes",
        "labelKey": "hr.employees.document.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-documents/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 100
  },
  {
    "key": "medical",
    "label": "Medical",
    "labelKey": "hr.employees.tabs.medical",
    "type": "resource",
    "fields": [
      {
        "key": "medical_type",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "value": "medical_checkup",
            "label": "Medical Checkup"
          },
          {
            "value": "fitness_to_work",
            "label": "Fitness to Work"
          },
          {
            "value": "drug_test",
            "label": "Drug Test"
          },
          {
            "value": "vaccination",
            "label": "Vaccination"
          },
          {
            "value": "vision_test",
            "label": "Vision Test"
          },
          {
            "value": "hearing_test",
            "label": "Hearing Test"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ],
        "tab": "medical",
        "label": "Medical Type",
        "labelKey": "hr.employees.medical.fields.medical_type",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "medical_type"
      },
      {
        "key": "event_date",
        "type": "date",
        "widget": "date",
        "tab": "medical",
        "label": "Event Date",
        "labelKey": "hr.employees.medical.fields.event_date",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "event_date"
      },
      {
        "key": "provider_name",
        "type": "text",
        "widget": "text",
        "tab": "medical",
        "label": "Hospital / Provider",
        "labelKey": "hr.employees.medical.fields.provider_name",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "provider_name"
      },
      {
        "key": "doctor_name",
        "type": "text",
        "widget": "text",
        "tab": "medical",
        "label": "Doctor",
        "labelKey": "hr.employees.medical.fields.doctor_name",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "doctor_name"
      },
      {
        "key": "result",
        "type": "text",
        "widget": "text",
        "tab": "medical",
        "label": "Result",
        "labelKey": "hr.employees.medical.fields.result",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "result"
      },
      {
        "key": "fitness_status",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "value": "not_applicable",
            "label": "Not Applicable"
          },
          {
            "value": "fit",
            "label": "Fit"
          },
          {
            "value": "fit_with_restriction",
            "label": "Fit With Restriction"
          },
          {
            "value": "temporary_unfit",
            "label": "Temporary Unfit"
          },
          {
            "value": "permanent_unfit",
            "label": "Permanent Unfit"
          }
        ],
        "tab": "medical",
        "label": "Fitness Status",
        "labelKey": "hr.employees.medical.fields.fitness_status",
        "default": "not_applicable",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "fitness_status"
      },
      {
        "key": "restriction_notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "medical",
        "label": "Restriction Notes",
        "labelKey": "hr.employees.medical.fields.restriction_notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "restriction_notes"
      },
      {
        "key": "next_due_date",
        "type": "date",
        "widget": "date",
        "tab": "medical",
        "label": "Next Due Date",
        "labelKey": "hr.employees.medical.fields.next_due_date",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "next_due_date"
      },
      {
        "key": "uploaded_file",
        "type": "file",
        "widget": "upload",
        "accept": [
          "pdf",
          "jpg",
          "jpeg",
          "png",
          "doc",
          "docx"
        ],
        "multiple": false,
        "category": "attachment",
        "public": false,
        "preview": true,
        "download": true,
        "replace": true,
        "delete": true,
        "upload_endpoint": "/api/uploads/",
        "tab": "medical",
        "label": "Attachment",
        "labelKey": "hr.employees.medical.fields.uploaded_file",
        "required": false,
        "layout": "full",
        "order": 90,
        "value_mode": "id",
        "upload_mode": "separate",
        "detail_field": "uploaded_file_detail",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "export": false,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "uploaded_file"
      },
      {
        "key": "is_confidential",
        "type": "boolean",
        "widget": "switch",
        "tab": "medical",
        "label": "Confidential",
        "labelKey": "hr.employees.medical.fields.is_confidential",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_confidential"
      },
      {
        "key": "is_verified",
        "type": "boolean",
        "widget": "switch",
        "tab": "medical",
        "label": "Verified",
        "labelKey": "hr.employees.medical.fields.is_verified",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_verified"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "medical",
        "label": "Active",
        "labelKey": "hr.employees.medical.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "medical",
        "label": "Notes",
        "labelKey": "hr.employees.medical.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-medical-events/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 110
  },
  {
    "key": "training",
    "label": "Training",
    "labelKey": "hr.employees.tabs.training",
    "type": "resource",
    "fields": [
      {
        "key": "training_category",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/training-categories/",
        "tab": "training",
        "label": "Training Category",
        "labelKey": "hr.employees.training.fields.training_category",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 10,
        "endpoint": "/api/administration/references/hr/lookup/training-categories/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "training_category_name"
      },
      {
        "key": "training_name",
        "type": "text",
        "widget": "text",
        "tab": "training",
        "label": "Training Name",
        "labelKey": "hr.employees.training.fields.training_name",
        "required": true,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "training_name"
      },
      {
        "key": "provider",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/training-providers/",
        "tab": "training",
        "label": "Training Provider",
        "labelKey": "hr.employees.training.fields.provider",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 30,
        "endpoint": "/api/administration/references/hr/lookup/training-providers/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "provider_name"
      },
      {
        "key": "start_date",
        "type": "date",
        "widget": "date",
        "tab": "training",
        "label": "Start Date",
        "labelKey": "hr.employees.training.fields.start_date",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "start_date"
      },
      {
        "key": "end_date",
        "type": "date",
        "widget": "date",
        "tab": "training",
        "label": "End Date",
        "labelKey": "hr.employees.training.fields.end_date",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 50,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "end_date"
      },
      {
        "key": "duration_hours",
        "type": "number",
        "widget": "number",
        "min": 0,
        "step": 0.01,
        "tab": "training",
        "label": "Duration (Hours)",
        "labelKey": "hr.employees.training.fields.duration_hours",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 60,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "duration_hours"
      },
      {
        "key": "score",
        "type": "number",
        "widget": "number",
        "min": 0,
        "step": 0.01,
        "tab": "training",
        "label": "Score",
        "labelKey": "hr.employees.training.fields.score",
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "order": 70,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "score"
      },
      {
        "key": "certificate_number",
        "type": "text",
        "widget": "text",
        "tab": "training",
        "label": "Certificate Number",
        "labelKey": "hr.employees.training.fields.certificate_number",
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "certificate_number"
      },
      {
        "key": "expiry_date",
        "type": "date",
        "widget": "date",
        "tab": "training",
        "label": "Expiry Date",
        "labelKey": "hr.employees.training.fields.expiry_date",
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "expiry_date"
      },
      {
        "key": "uploaded_file",
        "type": "file",
        "widget": "upload",
        "accept": [
          "pdf",
          "jpg",
          "jpeg",
          "png",
          "doc",
          "docx"
        ],
        "max_size_mb": 10,
        "multiple": false,
        "category": "attachment",
        "public": false,
        "preview": true,
        "download": true,
        "replace": true,
        "delete": true,
        "upload_endpoint": "/api/uploads/",
        "tab": "training",
        "label": "Attachment",
        "labelKey": "hr.employees.training.fields.uploaded_file",
        "required": false,
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 70,
        "value_mode": "id",
        "upload_mode": "separate",
        "detail_field": "uploaded_file_detail",
        "export": false,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "uploaded_file"
      },
      {
        "key": "is_mandatory",
        "type": "boolean",
        "widget": "switch",
        "tab": "training",
        "label": "Mandatory",
        "labelKey": "hr.employees.training.fields.is_mandatory",
        "default": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_mandatory"
      },
      {
        "key": "is_completed",
        "type": "boolean",
        "widget": "switch",
        "tab": "training",
        "label": "Completed",
        "labelKey": "hr.employees.training.fields.is_completed",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_completed"
      },
      {
        "key": "is_active",
        "type": "boolean",
        "widget": "switch",
        "tab": "training",
        "label": "Active",
        "labelKey": "hr.employees.training.fields.is_active",
        "default": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "placement": "quick",
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "is_active"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 3,
        "tab": "training",
        "label": "Notes",
        "labelKey": "hr.employees.training.fields.notes",
        "layout": "full",
        "table": false,
        "filter": false,
        "search": false,
        "sortable": false,
        "order": 140,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/employee-trainings/",
    "module": null,
    "foreignKey": "employee",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 120
  },
  {
    "key": "history",
    "label": "History",
    "labelKey": "hr.employees.fields.history",
    "type": "history",
    "fields": null,
    "modes": null,
    "endpoint": "/api/hr/employees/{employee_id}/employment-history/",
    "module": null,
    "foreignKey": null,
    "component": "EmployeesHistory",
    "icon": null,
    "readonly": true,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 130
  },
  {
    "key": "activity",
    "label": "Activity",
    "labelKey": "hr.employees.fields.activity",
    "type": "custom",
    "fields": null,
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": "EmployeesActivity",
    "icon": "activity",
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 140
  }
]

export const employeesWorkspaceDefaultTab: string =
  "general"

export const employeesOverviewItems: EmployeesOverviewItem[] =
  [
  {
    key: "employee_number",
    label: "Employee Number",
    fallback: "-",
  },
  {
    key: "first_name",
    label: "First Name",
    fallback: "-",
  },
  {
    key: "last_name",
    label: "Last Name",
    fallback: "-",
  },
  {
    key: "work_email",
    label: "Work Email",
    fallback: "-",
  },
  {
    key: "mobile",
    label: "Mobile",
    fallback: "-",
  },
  {
    key: "is_active",
    label: "Active",
    fallback: "-",
    format: "boolean",
  }
]