import type {
  VisitorRequestsWorkspaceTab,
} from "./composables/useVisitorRequestsWorkspace"

import type {
  VisitorRequestsOverviewItem,
} from "./components/VisitorRequestsOverview.vue"

export const visitorRequestsWorkspaceTabs: VisitorRequestsWorkspaceTab[] =
  [
  {
    "key": "general",
    "label": "Overview",
    "labelKey": "hr.visitor-requests.tabs.general",
    "type": "form",
    "fields": [
      "document_number",
      "request_date",
      "requester",
      "company",
      "location",
      "status"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 10
  },
  {
    "key": "visitor",
    "label": "Visitor Information",
    "labelKey": "hr.visitor-requests.tabs.visitor",
    "type": "form",
    "fields": [
      "visitor_type",
      "external_visitor",
      "visitor_name",
      "visitor_organization",
      "visitor_identity",
      "visitor_contact",
      "number_of_visitors"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 20
  },
  {
    "key": "visit",
    "label": "Visit Information",
    "labelKey": "hr.visitor-requests.tabs.visit",
    "type": "form",
    "fields": [
      "visit_purpose",
      "visit_type",
      "visit_start_date",
      "visit_start_time",
      "visit_end_date",
      "visit_end_time",
      "expected_duration_days",
      "remarks"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 30
  },
  {
    "key": "host",
    "label": "Host Information",
    "labelKey": "hr.visitor-requests.tabs.host",
    "type": "form",
    "fields": [
      "host_employee",
      "host_department",
      "host_position",
      "host_contact",
      "requester_department"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 40
  },
  {
    "key": "travel",
    "label": "Travel & Accommodation",
    "labelKey": "hr.visitor-requests.tabs.travel",
    "type": "form",
    "fields": [
      "travel_required",
      "travel_from",
      "travel_to",
      "departure_date",
      "departure_time",
      "return_date",
      "return_time",
      "transport_mode",
      "ticket_required",
      "ticket_number",
      "accommodation_required",
      "accommodation_type",
      "accommodation_name",
      "accommodation_checkin",
      "accommodation_checkout",
      "pickup_required",
      "pickup_point",
      "dropoff_point",
      "vehicle_required",
      "driver_required",
      "travel_remarks"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 50
  },
  {
    "key": "arrival",
    "label": "Arrival / Check-in",
    "labelKey": "hr.visitor-requests.tabs.arrival",
    "type": "form",
    "fields": [
      "arrival_status",
      "expected_arrival",
      "checked_in_at",
      "checked_in_by_name",
      "check_in_gate",
      "check_in_remarks",
      "checked_out_at",
      "checked_out_by_name",
      "check_out_remarks"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": false,
    "order": 60
  },
  {
    "key": "passes",
    "label": "Visitor Pass",
    "labelKey": "hr.visitor-requests.tabs.passes",
    "type": "resource",
    "fields": [
      {
        "key": "pass_number",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Pass No.",
        "labelKey": "hr.visitor-requests.passes.fields.pass_number",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": true,
        "overview": true,
        "disabled": true,
        "display": true,
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "pass_number"
      },
      {
        "key": "valid_from",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "Valid From",
        "labelKey": "hr.visitor-requests.passes.fields.valid_from",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "help_text": "Dikosongkan = ikut tanggal mulai kunjungannya.",
        "order": 80,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "valid_from"
      },
      {
        "key": "valid_until",
        "type": "date",
        "widget": "date",
        "tab": "general",
        "label": "Valid Until",
        "labelKey": "hr.visitor-requests.passes.fields.valid_until",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "help_text": "Dikosongkan = ikut tanggal selesai kunjungannya.",
        "order": 90,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "valid_until"
      },
      {
        "key": "status",
        "type": "select",
        "widget": "select",
        "options": [
          {
            "label": "Issued",
            "value": "issued"
          },
          {
            "label": "Returned",
            "value": "returned"
          },
          {
            "label": "Expired",
            "value": "expired"
          },
          {
            "label": "Lost",
            "value": "lost"
          }
        ],
        "tab": "general",
        "label": "Status",
        "labelKey": "hr.visitor-requests.passes.fields.status",
        "display_key": "status_label",
        "required": false,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "disabled": true,
        "display": true,
        "order": 100,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "status_label"
      },
      {
        "key": "issued_at",
        "type": "datetime",
        "widget": "datetime",
        "tab": "general",
        "label": "Issued At",
        "labelKey": "hr.visitor-requests.passes.fields.issued_at",
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "disabled": true,
        "display": true,
        "order": 110,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "issued_at"
      },
      {
        "key": "returned_at",
        "type": "datetime",
        "widget": "datetime",
        "tab": "general",
        "label": "Returned At",
        "labelKey": "hr.visitor-requests.passes.fields.returned_at",
        "required": false,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "disabled": true,
        "display": true,
        "order": 120,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "returned_at"
      },
      {
        "key": "notes",
        "type": "textarea",
        "widget": "textarea",
        "rows": 2,
        "tab": "general",
        "label": "Notes",
        "labelKey": "hr.visitor-requests.passes.fields.notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 130,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/hr/visitor-passes/",
    "module": "hr/visitor-passes",
    "foreignKey": "request",
    "component": null,
    "icon": null,
    "readonly": true,
    "disabled": false,
    "requiresRecord": true,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 70
  }
]

export const visitorRequestsWorkspaceDefaultTab: string =
  "general"

export const visitorRequestsOverviewItems: VisitorRequestsOverviewItem[] =
  [
  {
    key: "document_number",
    label: "Request No.",
    fallback: "-",
  },
  {
    key: "location_name",
    label: "Visit Location / Site",
    fallback: "-",
  },
  {
    key: "status_label",
    label: "Status",
    fallback: "-",
  },
  {
    key: "visitor_type_label",
    label: "Visitor Type",
    fallback: "-",
  },
  {
    key: "visitor_name",
    label: "Visitor Name",
    fallback: "-",
  },
  {
    key: "visit_purpose_name",
    label: "Visit Purpose",
    fallback: "-",
  },
  {
    key: "visit_start_date",
    label: "Visit Start Date",
    fallback: "-",
  },
  {
    key: "host_name",
    label: "Host Employee",
    fallback: "-",
  },
  {
    key: "arrival_status_label",
    label: "Arrival Status",
    fallback: "-",
  }
]