import type {
  RosterPoliciesWorkspaceTab,
} from "./composables/useRosterPoliciesWorkspace"

import type {
  RosterPoliciesOverviewItem,
} from "./components/RosterPoliciesOverview.vue"

export const rosterPoliciesWorkspaceTabs: RosterPoliciesWorkspaceTab[] =
  [
  {
    "key": "general",
    "label": "Scope",
    "labelKey": "hr.roster-policies.tabs.general",
    "type": "form",
    "fields": [
      "code",
      "name",
      "company",
      "location",
      "is_default",
      "description"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 10
  },
  {
    "key": "cycle",
    "label": "Cycle Pattern",
    "labelKey": "hr.roster-policies.tabs.cycle",
    "type": "form",
    "fields": [
      "cycle_work_days",
      "cycle_off_days",
      "roster_start_basis",
      "rolling_horizon_months",
      "cycle_length",
      "derived_ratio",
      "min_rest_hours"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 20
  },
  {
    "key": "travel",
    "label": "Travel Rules",
    "labelKey": "hr.roster-policies.tabs.travel",
    "type": "form",
    "fields": [
      "default_travel_out_days",
      "default_travel_in_days",
      "travel_day_mode",
      "travel_creates_segment",
      "travel_out_counts_as_roster_day",
      "travel_in_counts_as_roster_day",
      "count_transit_overnight",
      "travel_variance_credit_eligible",
      "travel_variance_credit_max_days"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 30
  },
  {
    "key": "credit",
    "label": "Rotation Credit",
    "labelKey": "hr.roster-policies.tabs.credit",
    "type": "form",
    "fields": [
      "credit_enabled",
      "conversion_ratio",
      "credit_rounding",
      "credit_carry_remainder",
      "credit_max_balance_days",
      "credit_expiry_months",
      "credit_allow_negative"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 40
  },
  {
    "key": "request",
    "label": "Request Rules",
    "labelKey": "hr.roster-policies.tabs.request",
    "type": "form",
    "fields": [
      "request_lead_days",
      "notify_lead_days",
      "urgent_purposes"
    ],
    "modes": null,
    "endpoint": null,
    "module": null,
    "foreignKey": null,
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": false,
    "inline": false,
    "canCreate": true,
    "showOnCreate": true,
    "order": 50
  },
  {
    "key": "shift_rotation",
    "label": "Shift Rotation",
    "labelKey": "hr.roster-policies.tabs.shift_rotation",
    "type": "resource",
    "fields": [
      {
        "key": "sequence",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Step",
        "labelKey": "hr.roster-policies.shift_rotation.fields.sequence",
        "required": true,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Urutan langkah. Sesudah langkah terakhir, perputaran kembali ke langkah pertama.",
        "order": 10,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "sequence"
      },
      {
        "key": "shift",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/hr/lookup/shifts/",
        "tab": "general",
        "label": "Shift",
        "labelKey": "hr.roster-policies.shift_rotation.fields.shift",
        "display_key": "shift_name",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Jamnya milik master Shift; mengubahnya di sana mengubah jadwal semua yang memakai pola ini.",
        "order": 20,
        "endpoint": "/api/administration/references/hr/lookup/shifts/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "shift_name"
      },
      {
        "key": "block_days",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Days",
        "labelKey": "hr.roster-policies.shift_rotation.fields.block_days",
        "required": true,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Berapa hari shift ini dipakai sebelum berganti. 7 = mingguan.",
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "block_days"
      },
      {
        "key": "notes",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Notes",
        "labelKey": "hr.roster-policies.shift_rotation.fields.notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/administration/references/hr/roster-shift-rotations/",
    "module": "hr/roster-shift-rotations",
    "foreignKey": "policy",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": true,
    "canCreate": true,
    "showOnCreate": true,
    "order": 55
  },
  {
    "key": "travel_days",
    "label": "Travel Days by POH",
    "labelKey": "hr.roster-policies.tabs.travel_days",
    "type": "resource",
    "fields": [
      {
        "key": "point_of_hire",
        "type": "lookup",
        "widget": "lookup",
        "lookup_endpoint": "/api/administration/references/geography/lookup/cities/",
        "tab": "general",
        "label": "Point Of Hire",
        "labelKey": "hr.roster-policies.travel_days.fields.point_of_hire",
        "display_key": "point_of_hire_name",
        "required": true,
        "table": true,
        "filter": true,
        "search": false,
        "sortable": true,
        "overview": true,
        "order": 10,
        "endpoint": "/api/administration/references/geography/lookup/cities/",
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "point_of_hire_name"
      },
      {
        "key": "travel_out_days",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Travel Out (days)",
        "labelKey": "hr.roster-policies.travel_days.fields.travel_out_days",
        "required": true,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Site → Point of Hire (pulang).",
        "order": 20,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "travel_out_days"
      },
      {
        "key": "travel_in_days",
        "type": "integer",
        "widget": "integer",
        "tab": "general",
        "label": "Travel In (days)",
        "labelKey": "hr.roster-policies.travel_days.fields.travel_in_days",
        "required": true,
        "table": true,
        "filter": false,
        "search": false,
        "sortable": true,
        "overview": true,
        "help_text": "Point of Hire → site (berangkat).",
        "order": 30,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "travel_in_days"
      },
      {
        "key": "notes",
        "type": "text",
        "widget": "text",
        "tab": "general",
        "label": "Notes",
        "labelKey": "hr.roster-policies.travel_days.fields.notes",
        "required": false,
        "table": true,
        "filter": false,
        "search": true,
        "sortable": false,
        "order": 40,
        "endpoint": null,
        "dependsOn": null,
        "lookupParams": {},
        "displayKey": "notes"
      }
    ],
    "modes": null,
    "endpoint": "/api/administration/references/hr/roster-travel-days/",
    "module": "hr/roster-travel-days",
    "foreignKey": "policy",
    "component": null,
    "icon": null,
    "readonly": false,
    "disabled": false,
    "requiresRecord": true,
    "inline": true,
    "canCreate": true,
    "showOnCreate": true,
    "order": 60
  }
]

export const rosterPoliciesWorkspaceDefaultTab: string =
  "general"

export const rosterPoliciesOverviewItems: RosterPoliciesOverviewItem[] =
  [
  {
    key: "code",
    label: "Code",
    fallback: "-",
  },
  {
    key: "name",
    label: "Name",
    fallback: "-",
  },
  {
    key: "cycle_work_days",
    label: "Work Days",
    fallback: "-",
  },
  {
    key: "cycle_off_days",
    label: "Field Break Days",
    fallback: "-",
  },
  {
    key: "default_travel_out_days",
    label: "Default Travel Out (days)",
    fallback: "-",
  },
  {
    key: "default_travel_in_days",
    label: "Default Travel In (days)",
    fallback: "-",
  }
]