export { default as DashboardHeader } from './components/DashboardHeader.vue'
export { default as DashboardKpi } from './components/DashboardKpi.vue'
export { default as DashboardInsights } from './components/DashboardInsights.vue'
export { default as DashboardFavoriteMenus } from './components/DashboardFavoriteMenus.vue'
export { default as DashboardQuickActions } from './components/DashboardQuickActions.vue'
export { default as DashboardNotifications } from './components/DashboardNotifications.vue'
export { default as DashboardWorkflow } from './components/DashboardWorkflow.vue'
export { default as DashboardApplications } from './components/DashboardApplications.vue'

export * from './types'
export * from './dummy'
export * from './mapper'
export * from './composables/useDashboard'
export * from './composables/useDashboardApi'